version: '3.3'
services:
    actual-http-api:
        container_name: actualhttpapi
        volumes:
            - './data:/data:rw'
        ports:
            - '5007:5007'
        env_file:
            - .env
        restart: on-failure
        image: jhonderson/actual-http-api:latest